### ISSUE TITLE
bind to last version of rtfeldman/elm-css

### ISSUE THREAD

**Issue by ubourdon** [Chadtech/elm-css-grid#1]
Need to bind lib to last [rtfeldman/elm-css lib](https://package.elm-lang.org/packages/rtfeldman/elm-css/16.0.0) (16.0.0)

**Comment by ubourdon** [comment]
cf. https://github.com/Chadtech/elm-css-grid/pull/2

**Comment by Chadtech** [comment]
Done! And published. The last `1.0.x` version of this package is on elm css `16.0.0` and all the `2.x.x` versions are.
